### ISSUE TITLE
电脑角落的涂鸦与oc tag翻新 | Underlake Reading Room

### ISSUE THREAD

**Issue by mazui3** [mazui3/comment#182]
https://mazui3.github.io/2021/04/05/P181/ 

 图片较乱,翻出了去年的小涂鸦来唠一唠oc相关.

**Comment by brutal588** [comment]
好棒！等有空我来系统学习（什么）o(*￣▽￣*)o

**Comment by mazui3** [comment]
> @brutal588
> 好棒！等有空我来系统学习（什么）o(*￣▽￣*)o

!!!感谢brutal感兴趣!!!
不过博客这边没好好整理过oc,之后再捣鼓捣鼓扩写一下.
时间太久东西杂,翻起来估计吃力,靠缘分认识好了(不是).

**Comment by brutal588** [comment]
> @mazui3
> > @brutal588
> > 好棒！等有空我来系统学习（什么）o(*￣▽￣*)o
> 
> !!!感谢brutal感兴趣!!!
> 不过博客这边没好好整理过oc,之后再捣鼓捣鼓扩写一下.
> 时间太久东西杂,翻起来估计吃力,靠缘分认识好了(不是).

相逢是缘。那再期待一下oc网站落成！到时候来参加剪彩仪式hhh

**Comment by mazui3** [comment]
> @brutal588
> > @mazui3
> > > @brutal588
> > > 好棒！等有空我来系统学习（什么）o(*￣▽￣*)o
> > 
> > !!!感谢brutal感兴趣!!!
> > 不过博客这边没好好整理过oc,之后再捣鼓捣鼓扩写一下.
> > 时间太久东西杂,翻起来估计吃力,靠缘分认识好了(不是).
> 
> 相逢是缘。那再期待一下oc网站落成！到时候来参加剪彩仪式hhh

谢谢谢谢…我会努力的……(握拳.jpg
